appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: qeXP8w89zlRq1SZYnxVtr447fwnUi+b3/ntgeZZcOJOI2kqsUMrNMsOWgzmZZ60e2QuBknfS7zTc14doq0vmLl1gk/8OBXuwYn2rB6q6x6n3hxcpg87kYFwlegJvaRKB4ZblELoGKl25aTD6eDoZrp6/3/nDnVXV9/gusLZLccYklGHiA1X9aOx9/HFhepY16KdFqMAy/b/jwxP6Ee8/4T1oxC6xMAQNX1SSpc6Tb+87vRT32miAFnQVb/zDY5d+0qMH/D6tUuhTnD6s5ixmHleuYSfThv9oiWrwEF1Rmz7wYuV9HFneizwki1Yve/oaMmnhRs7/JssnaNviv50m4W/fDWj1TptnDEHprkXhBxn7Sx0jzrUq1GEQ0WYEZrYzLhV2jLOjhGs5IANpHs6OsX6083/i3oSTJ5WLUl0fOH4ZNzOWrd2rds8JTachvBP6o+qvnGx3u5ZsOvObHngrUHGb29zAzQFYFVXQyhwvTEc4y2IK8dluYdl1Z2kjgocgVqWWe4qaeENdOipEOmKv2l7pGmRTk1zZpbBRj6nC2tElWYLl9wfbND999wEIk3lBb8sNqTzd7qIgR1oQpq3EO4VB9WZPiZXnKlpbIHFlIqz/B7Xc6NMkmPxO6BV6yoPfG3GOUhTthN6GwCzFKR42KVm/6OLPTYT3eooqyU/wChs=
conda_forge_output_validation: true
